### ISSUE TITLE
Missing cfg.json File

### ISSUE THREAD

**Issue by Hambaobao** [EleutherAI/sae#7]
Hello, I encountered a problem.
When running `saes = Sae.load_many_from_hub(sae_name_or_path)`, I get an error: `[Errno 2] No such file or directory: '/data1/HF-Models/EleutherAI/sae-llama-3-8b-32x/.huggingface/cfg.json'`.
I checked the repository on [Hugging Face](https://huggingface.co/EleutherAI/sae-llama-3-8b-32x/tree/main), but I could not find this file.
Was it possibly omitted during the upload?

**Comment by norabelrose** [comment]
Is this still happening with the latest commits?

**Comment by Hambaobao** [comment]
> Is this still happening with the latest commits?

yes, this is still happening.

**Comment by Lewington-pitsos** [comment]
I attempted to replicate this issue as of the current main HEAD `a81d89004ca9dec5c6ace0ed425a03ef6c265f44` and everything seems to work fine. @Hambaobao if you are still experiencing the issue can you post your current commit hash and the full code you used? thanks

my code:

```python
from sae import Sae

sae = Sae.load_from_hub("EleutherAI/sae-llama-3-8b-32x", hookpoint="layers.10")
```

Output
```
(v) root@bfecc2c92359:~/sae# python pad.py 
layers.10/cfg.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 92.0/92.0 [00:00<00:00, 574kB/s]
sae.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2.15G/2.15G [00:15<00:00, 143MB/s]
Fetching 2 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:15<00:00,  7.74s/it]
```

**Comment by Hambaobao** [comment]
> I attempted to replicate this issue as of the current main HEAD `a81d89004ca9dec5c6ace0ed425a03ef6c265f44` and everything seems to work fine. @Hambaobao if you are still experiencing the issue can you post your current commit hash and the full code you used? thanks
> 
> my code:
> 
> ```python
> from sae import Sae
> 
> sae = Sae.load_many_from_hub("EleutherAI/sae-llama-3-8b-32x")
> ```
> 
> Output
> 
> ```
> Fetching 66 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 66/66 [00:00<00:00, 9127.37it/s]
> ```

Thank you very much for your reply, I will check again.

**Comment by Lewington-pitsos** [comment]
@Hambaobao did it work out in the end mate?
